services:
  postgres:
    image: postgres:18
    container_name: purchase-invoices-db
    environment:
      POSTGRES_DB: purchase_invoices
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: purchase-invoices-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_KEY: ${API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres