spring.application.name=purchase_invoices

spring.datasource.url=jdbc:postgresql://localhost:5432/purchase_invoices
spring.datasource.username=invoice_app
spring.datasource.password=Pr9qwXDS55BSvkO4nauaJIyBerBpFc0x

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true